openapi: 3.0.3
info:
  title: LEGhub API Docs
  description: |-
    This documentation defines the endpoints that need to be implemented from the Electricity Network Operator (VNB) to receive Local Electricity Community (LEG) founding and participation data.
    
    The implementation is required to:
    * Handle future, unknown properties in addition to the properties that are listed here.
    * For optional properties, the value may be null, or the property may not be present at all.
    * If the response is a 4xx status code, the response body should contain a JSON object with a message property that describes the error.
    * If the response is a 5xx status code or no response is received, the request will be retried after some time.

  contact:
    email: fabian.boesiger@ajila.com
  version: 1.0.0
tags:
  - name: leg
    description: Everything about the leg.
  - name: measuringPoint
    description: Handling measuring points
paths:
  /legs:
    post:
      tags:
        - leg
      summary: A new LEG is founded
      description: Creates a new participation in the system
      operationId: createParticipation
      requestBody:
        description: Participation object that needs to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Leg'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LegCreationResponse'
        '400':
          description: Invalid data provided
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - apiKey:
            - write:leg
            - read:leg
  # /legs/{legId}:
  #   put:
  #     tags:
  #       - leg
  #     summary: An existing LEG is updated.
  #     description: Creates a new participation in the system
  #     operationId: createParticipation
  #     requestBody:
  #       description: Participation object that needs to be created
  #       content:
  #         application/json:
  #           schema:
  #             $ref: '#/components/schemas/Leg'
  #       required: true
  #     responses:
  #       '200':
  #         description: Successful operation
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/LegCreationResponse'
  #       '400':
  #         description: Invalid data provided
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/ErrorResponse'
  #     security:
  #       - apiKey:
  #           - write:leg
  #           - read:leg
  /measuringPoints:
    post:
      tags:
        - measuringPoint
      summary: A new measuring point is added to a participation
      description: Adds a new measuring point to an existing participation
      operationId: createMeasuringPoint
      requestBody:
        description: Measuring point object that needs to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MeasuringPoint'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MeasuringPointCreationResponse'
        '400':
          description: Invalid data provided
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - apiKey:
            - write:leg
            - read:leg
  # /measuringPoints/{measuringPointId}:
  #   put:
  #     tags:
  #       - measuringPoint
  #     summary: A new measuring point is added to a participation
  #     description: Updates an existing measuring point in the system
  #     operationId: createMeasuringPoint
  #     requestBody:
  #       description: Measuring point object that needs to be created
  #       content:
  #         application/json:
  #           schema:
  #             $ref: '#/components/schemas/MeasuringPoint'
  #       required: true
  #     responses:
  #       '200':
  #         description: Successful operation
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/MeasuringPointCreationResponse'
  #       '400':
  #         description: Invalid data provided
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/ErrorResponse'
  #     security:
  #       - apiKey:
  #           - write:leg
  #           - read:leg
components:
  schemas:
    Leg:
      type: object
      description: Represents a participation (LEG or VZEV)
      required:
        - leghubId
        - pricing
        - discountLevel
        - address
        - founder
        - eicCode
        - netzebene
      properties:
        leghubId:
          type: string
          format: uuid
          example: f4fcfdcf-700c-4364-88ff-d7c6fab02bf6
          description: Unique identifier for the participation in LEGhub
        externalId:
          type: string
          description: Only available if an external leg ID was returned in the creation response
          example: null
        name:
          type: string
          example: Bauernhof Rüti
          description: Name of the participation
        eicCode:
          type: string
          example: 12X1234
          description: X-Code des VNB
        discountLevel:
          type: string
          enum:
            - HIGH
            - LOW
          description: The discount level applied to the participation
        startingDate:
          type: string
          format: date
          description: The date when the participation starts to be active (ISO format)
        referenceAddress:
          $ref: '#/components/schemas/Address'
        netzebene:
          $ref: '#/components/schemas/Netzebene'
        pricing:
          $ref: '#/components/schemas/Pricing'
        founder:
          $ref: '#/components/schemas/Contact'
    Netzebene:
      type: object
      description: Network level information
      required:
        - trafostation
      properties:
        trafostation:
          type: string
          description: Transformer station identifier
        unterwerk:
          type: string
          description: Substation identifier (optional)
    Address:
      type: object
      description: Represents a physical address
      required:
        - street
        - houseNumber
        - zipCode
        - city
      properties:
        street:
          type: string
          example: Hauptstrasse
          description: Street name
        houseNumber:
          type: string
          example: "12"
          description: House number
        zipCode:
          type: string
          example: "8000"
          description: Postal code
        city:
          type: string
          example: Zürich
          description: City name
    Contact:
      type: object
      description: Represents contact information for a person or company
      required:
        - firstName
        - lastName
        - email
        - address
        - businessPartnerNumber
        - legalForm
      properties:
        businessPartnerNumber:
          type: string
          example: "123456789"
          description: The business partner number (Kundennummer) of the contact at the VNB
        firstName:
          type: string
          example: Max
          description: First name of the contact person
        lastName:
          type: string
          example: Mustermann
          description: Last name of the contact person
        email:
          type: string
          format: email
          example: max.muster@example.com
          description: Email address
        phone:
          type: string
          example: +41 79 123 45 67
          description: Phone number
        uid:
          type: string
          example: CHE-123.456.789
          description: VAT number (UID)
        legalForm:
          type: string
          enum:
            - PRIVATPERSON
            - UNTERNEHMEN
            - LOKALE_BEHOERDE
            - VEREIN
            - GENOSSENSCHAFT
            - STIFTUNG
            - ANDERE
          description: Legal form of the contact
        legalName:
          type: string
          example: Muster AG
          description: Legal name (only provided when legalForm is not PRIVATE_PERSON)
        address:
          $ref: '#/components/schemas/Address'
    Pricing:
      type: object
      description: Represents pricing information for a participation
      required:
        - pricingModel
        - minimumTermMonths
        - billingResponsibility
      properties:
        pricingModel:
          type: string
          enum:
            - STANDARD_TARIFF
            - INDIVIDUAL_FIXED_PRICE
            - CUSTOMIZED_STANDARD_TARIFF
            - CUSTOMIZED_PRIZING_MODEL
          description: The pricing model used for the participation
        individualFixedPrice:
          type: number
          format: float
          description: Only provided if the pricingModel is INDIVIDUAL_FIXED_PRICE
        customizedStandardTariffDiscount:
          type: number
          format: float
          description: Only provided if the pricingModel is CUSTOMIZED_STANDARD_TARIFF
        minimumTermMonths:
          type: integer
          minimum: 0
          description: The minimum term in months for joining the participation
        billingResponsibility:
          type: string
          enum:
            - VNB
            - FOUNDER
          description: Whether the founder or the VNB is responsible for billing
    MeasuringPoint:
      type: object
      description: Represents a measuring point in the system
      required:
        - leghubLegId
        - externalLegId
        - measuringPointNumber
        - address
        - owner
      properties:
        leghubLegId:
          type: string
          format: uuid
          example: f4fcfdcf-700c-4364-88ff-d7c6fab02bf6
          description: The participation ID as provided by LEGhub
        externalLegId:
          type: string
          description: Only available if an external participation ID was returned in the creation response
          example: null
        measuringPointNumber:
          type: string
          example: CH1234567890123456789012345678901
          description: The measuring point number as provided by the electricity network operator
        role:
          type: string
          enum:
            - CONSUMPTION
            - PRODUCTION
        startingDate:
          type: string
          format: date
        power:
          type: number
          format: float
          description: The production/consumption power (depending on the measuring point type) of the measuring point in kW
        referenceAddress:
          $ref: '#/components/schemas/Address'
        owner:
          $ref: '#/components/schemas/Contact'
    MeasuringPointCreationResponse:
      type: object
      description: Response object for measuring point creation
    LegCreationResponse:
      type: object
      description: Response object for participation creation
      properties:
        externalId:
          type: string
          example: 123456-000001
          description: |-
            An optional external id provided by the electricity network operator. Providing a unique id is
            highly reccomended per LEG manual or "LEG Handbuch":
            LEG werden durch eindeutige Nummern identifiziert, die von den Netzbetreibern vergeben werden.
            Jede LEG-Nummer besteht aus 6 Zeichen zur Kennzeichnung der Netzzugehörigkeit, gefolgt von ei-
            nem Bindestrich und 6 weiteren Zeichen, die eine eindeutige Identifikation innerhalb des Netzes er-
            möglichen. Der Netzbetreiber gewährleistet die Eindeutigkeit und Dauerhaftigkeit dieser Nummer. Die
            Verwendung sprechender Schlüssel ist unzulässig. Die LEG-Nummer wird nur einmal vergeben und
            bleibt dauerhaft gültig - auch im Falle einer Auflösung der LEG.
    ErrorResponse:
      type: object
      description: Standard error response object
      required:
        - errorCode
      properties:
        message:
          type: string
          example: Invalid data provided
          description: A message describing the error
        clientMessage:
          type: string
          example: Die Kundennummer ist unbekannt.
          description: A message that can be shown to the user
        errorCode:
          type: string
          enum:
            - INVALID_STARTING_DATE
            - INVALID_ADDRESS
            - INVALID_PRICING
            - INVALID_MEASURING_POINT_NUMBER
            - INVALID_BUSINESS_PARTNER_NUMBER
            - INVALID_EXTERNAL_LEG_ID
            - INVALID_EIC_CODE
            - MEASURING_POINT_BUSINESS_PARTNER_NUMBER_MISMATCH
            - CONTACT_ADDRESS_BUSINESS_PARTNER_NUMBER_MISMATCH
            - MEASURING_POINT_ADDRESS_MISMATCH
            - INAPPROPRIATE_NAME
            - OTHER
          description: The type of error that occurred
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: X-Api-Key
